/**
 * Services Index
 * فهرس الخدمات
 */

// Export BilingualText from public types (common type used everywhere)
export type { BilingualText, PaginationMeta } from './public/types';

// Auth service
export {
  type User,
  type LoginCredentials,
  type RegisterData,
  type LoginResponse,
  tokenUtils,
  authService,
} from './auth.service';

// Re-export admin services (excluding BilingualText to avoid conflict)
export {
  // Settings
  type Settings,
  type GeneralSettings,
  type ContactSettings,
  type SocialSettings,
  type SEOSettings,
  type FeatureSettings,
  type ThemeSettings,
  getSettings,
  updateSettings,
  updateSettingsSection,
  settingsService,
  // Content
  type ContentItem,
  type ContentType,
  type ContentFilters,
  type CreateContentData,
  type UpdateContentData,
  getAllContent,
  getContentByKey,
  createContent,
  updateContent,
  deleteContent,
  bulkUpsertContent,
  contentService,
  // Translations
  type TranslationItem,
  type TranslationFilters,
  type CreateTranslationData,
  type UpdateTranslationData,
  getAllTranslations,
  getTranslation,
  getByNamespace,
  getAllByLocale,
  getNamespaces,
  searchTranslations,
  createTranslation,
  updateTranslation,
  upsertTranslation,
  bulkUpsertTranslations,
  deleteTranslation,
  translationsService,
  // Menus
  type MenuItem,
  type Menu,
  type MenuLocation,
  type MenuItemType,
  type MenuItemTarget,
  type MenuFilters,
  type CreateMenuData,
  type UpdateMenuData,
  type CreateMenuItemData,
  getMenuByLocation,
  getMenuBySlug,
  getAllMenus,
  getMenu,
  createMenu,
  updateMenu,
  deleteMenu,
  addMenuItem,
  updateMenuItem,
  removeMenuItem,
  reorderMenuItems,
  menusService,
} from './admin';

// Re-export public services (excluding BilingualText to avoid conflict)
export {
  // Services
  type ServiceCategory,
  type ServiceFeature,
  type ServicePricingPlan,
  type ServiceFAQ,
  type ServiceProcessStep,
  type Service,
  type ServicesFilters,
  type ServicesResponse,
  getServices,
  getServiceBySlug,
  getFeaturedServices,
  getServiceCategories,
  getServicesByCategory,
  searchServices,
  servicesService,
  // Projects
  type ProjectTechnology,
  type ProjectTestimonial,
  type ProjectCategory,
  type Project,
  type ProjectsFilters,
  type ProjectsResponse,
  getProjects,
  getProjectBySlug,
  getFeaturedProjects,
  getProjectCategories,
  getProjectsByCategory,
  searchProjects,
  projectsService,
  // Team
  type SocialLinks,
  type Skill,
  type Department,
  type TeamMember,
  type TeamFilters,
  type TeamResponse,
  getTeamMembers,
  getTeamMemberBySlug,
  getFeaturedTeamMembers,
  getDepartments,
  getTeamMembersByDepartment,
  teamService,
  // Contact
  type ContactFormData,
  type ContactResponse,
  type NewsletterData,
  type NewsletterResponse,
  submitContactForm,
  subscribeNewsletter,
  unsubscribeNewsletter,
  contactService,
} from './public';
